spring.application.name=TpProjet
spring.datasource.url=jdbc:mysql://host.docker.internal:3306/TPFoyer?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
server.port=8034
server.servlet.context-path=/tp-foyer
mapstruct.defaultComponentModel=spring
mapstruct.disableBuilders=true